[project]
name = "caltechdata"
description = "The Caltech institutional data repository"
readme = "README.md"
version = "13.1.0"
requires-python = ">= 3.12"

dependencies = [
  "invenio-app-rdm[opensearch2, s3]~=13.1.0",
  "invenio-saml",
  "setuptools<82",
  "sentry-sdk>=1.45,<2.0.0",
  "python-dotenv>=0.21.0",
  "uwsgi>=2.0",
  "uwsgitop>=0.11",
  "uwsgi-tools>=1.1.1",
  "lxml-html-clean>=0.1.1",
]

tests = [
    "pytest-invenio>=3.0.0,<4.0.0",
]

[dependency-groups]
dev = [
    "flask-debugtoolbar>=0.16.0",
    "pytest-invenio>=3.0.0,<4.0.0",
]

[tool.uv]
no-binary-package = [
    "lxml",
    "xmlsec"
]

[tool.uv.sources]
invenio-saml = { git = "https://github.com/caltechlibrary/invenio-saml", tag = "maint-v1.x" }
